---
jobs:
- name: build-resource-image
  plan:
  - get: source-code
    trigger: true
  - put: docker-hub
    params:
      build: source-code


resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:ECSTeam/cfops-image.git
    branch: master
    private_key: {{github-private-key}}
- name: docker-hub
  type: docker-image
  source:
    repository: jghiloni/cfops
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
